version: '3'

services:
   mysql:
        image: mysql:5.7.29
        container_name: "mysql"
        environment:
            MYSQL_ROOT_PASSWORD: "MyNewPass1!"
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "./db_storage:/var/lib/mysql"
            - "./config/mysql/my.cnf:/etc/my.cnf"
            - "./config/mysql/init:/docker-entrypoint-initdb.d/"
        networks:
            - app_net

networks:
 app_net:
     driver: bridge
     ipam:
         config:
             - subnet: 172.26.0.0/24