version: '3'

services:
   proxy_server:
        image: nginx:1.19.10
        ports:
            - "443:443"
            - "3307:3307"
            - "444:444"
            - "80:666"
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "./project:/src"
            - "./config/nginx/conf.d:/etc/nginx/conf.d"
            - "./config/nginx/default.d:/etc/nginx/default.d"
            - "./config/nginx/log:/var/log/nginx"
            - "./config/nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "./frontend:/var/frontend"
        container_name: "proxy_server"
        restart: always
        depends_on:
            - web
        networks:
            - app_net
   web:
    image: app/web
    container_name: "app_web"
    command: bash -c "python hello.py"
    ports:
        - "8000:8000"
    volumes:
        - "/etc/localtime:/etc/localtime:ro"
        - "./project:/src"
        - "/proc:/hostip/:ro"
    restart: always
    privileged: true
    networks:
            - app_net

networks:
    app_net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.26.0.0/24