version: '3'

services:
  redis:
    image: redis:5.0.7
    container_name: redis
    command: "redis-server /etc/redis/redis.conf"
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./redis_stroage:/data"
      - "./config/redis/redis.conf:/etc/redis/redis.conf:ro"
    networks:
      - app_net

networks:
 db_net:
     driver: bridge
     ipam:
         config:
             - subnet: 172.26.0.0/24