version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: ipsla-es-cluster
    environment:
      - node.name=es01
      - cluster.name=ipsla-es-cluster
      #- cluster.initial_master_nodes=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    restart: always
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
      - ./config/es:/usr/share/elasticsearch/config
      - ./es_logs:/usr/share/elasticsearch/logs
    networks:
      - elastic

  logstash:
    image: cisco/logstash:7.16.2
    container_name: ipsla-logstash
    restart: always
    ports:
      - 10014:10014/udp
      - 10014:10014/tcp
    volumes:
      - ./logstash_data:/usr/share/logstash/data
      - ./logstash_pipeline:/usr/share/logstash/pipeline
      - ./config/logstash:/usr/share/logstash/config
    networks:
      - elastic

networks:
  elastic:
    driver: bridge